### ISSUE TITLE
Deploy to RStudio Connect

### ISSUE THREAD

**Issue by ChrisBeeley** [ThinkR-open/fusen#114]
Hello- I just found this package and I absolutely love it 🙌 

I'm wondering how to deploy a report to be rerun on a schedule to RStudio Connect. In the typical `golem` workflow there's a function for that and without that function I'm a bit lost as to how best to do it. I can think of a few ways but they all seem a bit stupid so I wondered if there was a canonical way to do it.

**Comment by statnmap** [comment]
Thanks.  

{fusen} creates a package structure. As you have some vignettes inside, you can build the {pkgdown} website of your package with continuous integration and deploy it from your Git repository on Connect.  
The article part of the pkgdown can be your report.  

However, you probably speak about a report that would use the functions of your package but with a different (or bigger version of) input dataset than the one you include in your reproducible examples and unit tests.  
Then, I suggest to have a "report.Rmd" at the root of your package which uses the functions of your package. When you send it to Connect, you send also the rest of the package so that functions are available.  

- You need to hide this file from build: `usethis::use_build_ignore("report.Rmd")`
- You need to load your package using `pkgload::load_all()` at the top of the "report.Rmd" file because the package does not really exists (instead of `library(mypackage)`.

That would be even better to store this report in a sub-directory like "report/", so that the package is clean, but I did not explore how this would be possible to send it properly to Connect. Maybe with an equivalent of app.R for shiny.

**Comment by ChrisBeeley** [comment]
Aha! Yes, I was doing something a lot stupider than that, as I predicted. It does work in a report/ folder, as well, so that's a good thought.

Thanks!
