### ISSUE TITLE
Check DESCRIPTION in `fusen::fill_description()`

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#27]
- [x] Verify that Title has title case
- [x] Verify that Description as a dot at the end
- [ ] Add a "Please correct and re-run fill_description()"

These are too frequent errors that can be checked and corrected.

**Comment by dmi3kno** [comment]
Since you are creating DESCRIPTION file with {usethis} shouldnt it be in there already (validating the fields before they are written to disk?).

I think {desc} has some of the checks. You might want to see how it is done there, if you dont want to import a dependency. This is also useful for {golem}.

**Comment by statnmap** [comment]
usethis only checks for the package name.

Add {desc} is not implemented yet...
![image](https://user-images.githubusercontent.com/21193866/126879924-1e745328-ce08-4027-b1f0-f7bcb6c212a6.png)

**Comment by dmi3kno** [comment]
That's pretty sad. Rcheck catches it somehow, but I guess the validation is baked into R and not callable directly.
