### ISSUE TITLE
All filenames should be saved with tolower()

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#31]
To avoid incompatibilities with MacOS.  

- R/ files
- tests/ files
- vignettes

**Comment by novica** [comment]
Hi @statnmap I found your https://rtask.thinkr.fr/when-development-starts-with-documentation/ extremely helpful when I was working on my first package, only to see now that you have built `fusen`.

I would like to help with some of the issues here. Can you provide a little more context about what this issue is about?

**Comment by statnmap** [comment]
Hi. Thank you.
{fusen} uses the name of the functions to create the R files in the R/ directory and the tests/ directory.  
If a function is the following:

```r
#' Title
MyFunction <- function() {
  message("hello")
}
```
Then files will be : `MyFunction.R` and `tests-MyFunction.R`.  
Having filenames with uppercase is a bad idea because of OS incompatibilities.  
I would like to be sure that all filenames created by {fusen} are lowercase, withtout special characters.

There is already a function named `asciify_name()` inside the package that should be enough to pass just before writing file names. Indeed, I think this already fixes the filename for the vignette.

If you feel comfortable with unit tests too, you can also add the above code in a new section + function chunk inside the "inst/tests-templates/dev-template-test.Rmd" to be sure the output is the expected one. This may break some existing unit tests counting the number of files created though.

Thank you.
