### ISSUE TITLE
inflate overwrites DESCRIPTION FILE whether overwrite=TRUE or FALSE in dev_history.Rmd

### ISSUE THREAD

**Issue by Ben-Cox** [ThinkR-open/fusen#5]
Whenever I run inflate() it is overwriting the DESCRIPTION file and it doesn't write the Depends field in the {r description} chunk.  Is the DESCRIPTION file written by the description chunk in the dev_history.RMD? How do i add dependencies to the DESCRIPTION file when they are overwritten by inflate?

**Comment by statnmap** [comment]
The list of dependencies is updated automatically with `attachment::att_amend_desc()` when using `inflate()`. This function is supposed to find all required dependencies in your package, coming from `@importFrom`, but also calls to `library()` in the vignettes. Most of the time, if {attachment} did not detect a dependency, it is because it is not declared in the code.  
There are a few corner cases though, for which I could add parameters in `inflate()`.

**Comment by Ben-Cox** [comment]
Thanks for the reply. Im still not clear how the package dependencies are parsed from `dev_history.Rmd`. I have a package for personal use (won't be submitted to CRAN) that does a bunch of data manipulation to some specific data and I want to make use of `dplyr` throughout but I don't want to use `dplyr::fun()` every time. How do I get `inflate()` to write `dplyr` to `Depends` in the DESCRIPTION file from `dev_history.Rmd` or should just avoid that as bad practice and use `dplyr::fun()` every time? 

On a side note, why is the package created by `fusen::inflate()`  exporting the pipe `%>%` in the NAMESPACE? I don't see where that is coming from.

**Comment by statnmap** [comment]
You need to document your functions with a Roxygen skeleton. If you don't want to use `pkg::fun()`, you will add `@importFrom pkg fun`. There is no other way of doing it.  
You can read this chapter for more information on imports : https://r-pkgs.org/namespace.html#imports
